name: Deploy Cloud Function (Auto)

on:
  push:
    branches:
      - main
    paths:
      - "firebase/function/**"
      - ".github/workflows/deploy_cloud_function_auto.yaml"

defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: ./firebase/function

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: dev
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: deploy-cloud-function-dev
      cancel-in-progress: false
    
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
        with:
          enable-cache: true
          activate-environment: true
          working-directory: firebase/function

      - name: Set up Python
        run: |
          curl -s https://mise.run | sh
          uv python install 3.13

      - name: Authenticate GCP
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.ACTIONS_RUNNER_SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy create-user function
        run: |
          gcloud functions deploy create-user \
            --region=asia-northeast1 \
            --runtime=python313 \
            --source=functions \
            --entry-point=create_user \
            --service-account=${{ vars.DEV_FIREBASE_AUTH_FUNCTION_SERVICE_ACCOUNT }} \
            --allow-unauthenticated \
            --gen2 \
            --trigger-http

      - name: Deploy update-user function
        run: |
          gcloud functions deploy update-user \
            --region=asia-northeast1 \
            --runtime=python313 \
            --source=functions \
            --entry-point=update_user \
            --service-account=${{ vars.DEV_FIREBASE_AUTH_FUNCTION_SERVICE_ACCOUNT }} \
            --allow-unauthenticated \
            --gen2 \
            --trigger-http

  deploy-stg:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: stg
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: deploy-cloud-function-stg
      cancel-in-progress: false
    needs: deploy-dev
    
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
        with:
          enable-cache: true
          activate-environment: true
          working-directory: firebase/function

      - name: Set up Python
        run: |
          curl -s https://mise.run | sh
          uv python install 3.13

      - name: Authenticate GCP
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.ACTIONS_RUNNER_SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy create-user function
        run: |
          gcloud functions deploy create-user \
            --region=asia-northeast1 \
            --runtime=python313 \
            --source=functions \
            --entry-point=create_user \
            --service-account=${{ vars.STAGING_FIREBASE_AUTH_FUNCTION_SERVICE_ACCOUNT }} \
            --allow-unauthenticated \
            --gen2 \
            --trigger-http

      - name: Deploy update-user function
        run: |
          gcloud functions deploy update-user \
            --region=asia-northeast1 \
            --runtime=python313 \
            --source=functions \
            --entry-point=update_user \
            --service-account=${{ vars.STAGING_FIREBASE_AUTH_FUNCTION_SERVICE_ACCOUNT }} \
            --allow-unauthenticated \
            --gen2 \
            --trigger-http

  deploy-prod:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: prod
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: deploy-cloud-function-prod
      cancel-in-progress: false
    needs: deploy-stg
    
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
        with:
          enable-cache: true
          activate-environment: true
          working-directory: firebase/function

      - name: Set up Python
        run: |
          curl -s https://mise.run | sh
          uv python install 3.13

      - name: Authenticate GCP
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.ACTIONS_RUNNER_SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy create-user function
        run: |
          gcloud functions deploy create-user \
            --region=asia-northeast1 \
            --runtime=python313 \
            --source=functions \
            --entry-point=create_user \
            --service-account=${{ vars.PROD_FIREBASE_AUTH_FUNCTION_SERVICE_ACCOUNT }} \
            --allow-unauthenticated \
            --gen2 \
            --trigger-http

      - name: Deploy update-user function
        run: |
          gcloud functions deploy update-user \
            --region=asia-northeast1 \
            --runtime=python313 \
            --source=functions \
            --entry-point=update_user \
            --service-account=${{ vars.PROD_FIREBASE_AUTH_FUNCTION_SERVICE_ACCOUNT }} \
            --allow-unauthenticated \
            --gen2 \
            --trigger-http
